# Generated by Django 5.2.8 on 2025-11-26 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Webhook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.URLField()),
                ('event_type', models.CharField(choices=[('product_imported', 'Product Imported'), ('product_updated', 'Product Updated')], max_length=50)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
    ]
